### ISSUE TITLE
youtubeのプレビュー幅について

### ISSUE THREAD

**Issue by toshimay** [akoya-tomo/koshian_autolink_futaba_kai#1]
度々失礼します。
こちらのアドオンでyoutubeのURLも[見る][隠す]といった形でレス上でプレビューできるようになるのですが、最大幅の設定が反映されず、非常に小さい画面になってしまいます。
塩のリンク画像などは正常に反映されています。
こちらの環境のせいなのかアドオンの仕様なのかが判別つかず、コメントさせていただきました。
もし仕様であればyoutubeのリンクも幅を変更できるようにすることは可能でしょうか？

**Comment by akoya-tomo** [comment]
調べてみたところ最大幅の設定は機能しているのですが、YouTube側が表示する埋め込み用のプレイヤーが最大幅よりも小さいため、結果として小さいサイズになっているようです。
こちらからプレイヤーのサイズを指定すれば最大幅で表示できそうです。
「Youtubeのプレビューを常に最大横幅で表示する」オプションを有効にしたら、YouTubeのプレビューの横幅を最大横幅に固定するようにしようかなと考えていますが、いかがでしょうか。

**Comment by toshimay** [comment]
ありがとうございます。
HTML覗いてみても指定した幅が反映されてたので何でかなぁ…と思ってたんですが、そういうことだったんですね。
ご提案いただいた形で良いと思います！

**Comment by akoya-tomo** [comment]
試しにテスト版を作ってみました。
https://github.com/akoya-tomo/koshian_autolink_futaba_kai/releases/download/v1.2.0b6/koshian_autolink_futaba_kai-1.2.0b6-an+fx.xpi
使い勝手を考慮して通常のプレビュー幅とは別にYouTubeのプレビュー幅を設定できるようにしました。
ご確認お願いします。

**Comment by toshimay** [comment]
動作確認できました。
求めていた機能がここに…別設定もとてもありがたいです。
いつもありがとうございます！助かります。

**Comment by akoya-tomo** [comment]
ご希望に添えたようでなによりです。
明日にでも正式リリースしようと思います。
また要望とかあればいつでもお気軽にどうぞ。
